In [2]:
import pandas as pd

In [ ]:
# read in Aluminium trade data from UN comtrade database (https://comtradeplus.un.org/)
# trade data available from 1988 on
# use Imports and Exports for – HS 7601 (Unwrought aluminium), 7602 (Aluminium waste and scrap) for all regions
# for now exclude  7603–7616 (final products to avoid double counting) - could be worth to check later
# read in in 4 steps, as database does not allow selection of more years at once

alu_1988_1999 = pd.read_csv('alu_trade_1988_1999_qty.csv', 
                   encoding="iso-8859-1", index_col=False)

alu_2000_2011 = pd.read_csv('alu_trade_2000_2011_qty.csv', 
                     encoding="iso-8859-1", index_col=False)

alu_2012_2023 = pd.read_csv('alu_trade_2012_2023_qty.csv', 
                   encoding="iso-8859-1", index_col=False)

alu_2024 = pd.read_csv('alu_trade_2024_qty.csv',
                   encoding="iso-8859-1", index_col=False)

alu_trade = pd.concat([alu_1988_1999, alu_2000_2011, alu_2012_2023, alu_2024])

     qtyUnitCode qtyUnitAbbr           qty
0              8          kg  2.601219e+06
1              8          kg  8.179617e+08
2              8          kg  2.109154e+06
3              8          kg  4.671712e+07
4              8          kg  2.357962e+07
..           ...         ...           ...
293           -1         NaN  0.000000e+00
294            8          kg  2.053051e+09
295            8          kg  4.000000e+04
296            8          kg  7.169740e+06
297            8          kg  2.214260e+06

[15786 rows x 3 columns]

      qtyUnitCode qtyUnitAbbr         qty
0               8          kg  9945937.00
1               8          kg  1939745.00
2               8          kg  5733780.00
3               8          kg       80.00
4               8          kg   427825.00
...           ...         ...         ...
6418            8          kg  8437420.00
6419            8          kg     2557.18
6420            8          kg  4292319.00
6421            8          kg  1573920.00
6422            8          kg     3400.00

[6423 rows x 3 columns]